### PR TITLE
Major Update (Fix Header, Footer, and Links)

### PR DESCRIPTION
**Pull request by thekodester**
Header and footer have been updated with correct links. Also I went with disabling French lanuage selection. More details in PR #231.

### CODE REVIEW

**Comment by thekodester** [comment]
@namjohn920 @duboisp

**Comment by thekodester** [comment]
@duboisp @GormFrank @juleskuehn @namjohn920

wet-boew/wet-boew#8458

**Comment by thekodester** [comment]
This PR is now 52 commits behind probably be simpler to recreate the PR than attempting to update this one to match (due to conflicts).

I don't mind doing that but only if their actual interest in fixing the issue with this repo and merging the PR before it going stale again.

**Comment by juleskuehn** [comment]
It's too bad this went stale.
I think you will have much better success getting PRs merged by making more minimal changes in each PR and clearly describing the purpose of each. This one had so many lines of code changed that it was daunting to review.

**Pull request closed without merging**
